/**
 * Auto-Pilot 超级 Prompt 生成器
 * 将 Pipeline 的所有步骤打包成单次可执行的链式指令
 * 粘贴到 AI 编辑器后，AI 自动链式执行所有步骤，无需手动推进
 */

import type { PipelineDefinition, SkillDefinition } from '../skills/types';

export interface AutopilotOptions {
  context: string;
  isEn?: boolean;
}

/** 生成单条 Pipeline 的超级 prompt */
export function buildAutopilotPrompt(
  pipeline: PipelineDefinition,
  skills: SkillDefinition[],
  options: AutopilotOptions
): string {
  const { context, isEn = false } = options;
  const total = skills.length;

  if (isEn) {
    const header = `# Auto-Pilot Workflow Instruction

**Context**: ${context}
**Pipeline**: ${pipeline.name} (\`${pipeline.id}\`)
**Total Steps**: ${total}
**Mode**: Fully automatic — no user confirmation between steps`;

    const rules = `## Execution Rules (Must Follow)

1. Execute all ${total} steps below **in order without waiting for user confirmation**
2. After each step completes, wrap the output with \`<details>\` collapse tags (see format below)
3. Pass each step's **core output** (≤200 word summary) as background context to the next step
4. After all steps complete, output a single merged final report`;

    const foldFormat = `## Output Format for Each Step

After each step completes, use this exact format:

\`\`\`
<details>
<summary>✅ Step N: [Skill Name] — Completed</summary>

[Full output of this step]

</details>
\`\`\``;

    const stepsSection = skills.map((skill, i) => {
      const stepNum = i + 1;
      const prevNote = i > 0
        ? `**Prior Input**: Use the core output of Step ${i} as background context for this step.\n\n`
        : '';
      const stepsContent = skill.steps
        .map((s, si) => {
          const title = s.title.replace(/^\d+[.、]\s*/, '');
          const indented = s.content.split('\n').map((l) => `   ${l}`).join('\n');
          return `   ${si + 1}. **${title}**\n${indented}`;
        })
        .join('\n\n');

      return `### Step ${stepNum}/${total}: ${skill.nameEn.replace(/_/g, ' ')}

${prevNote}**Goal**: ${skill.descriptionEn ?? skill.description}

**Execution Steps**:

${stepsContent}

**Output Format**: ${skill.outputFormat}`;
    }).join('\n\n---\n\n');

    const reportTemplate = buildReportTemplate(pipeline, skills, context, true);
    const startCmd = `**Begin executing Step 1 now.**`;

    return [header, '---', rules, '---', foldFormat, '---', `## Step Details`, stepsSection, '---', reportTemplate, startCmd].join('\n\n');
  }

  // 中文版
  const header = `# Auto-Pilot 工作流指令

**任务背景**：${context}
**Pipeline**：${pipeline.name}（\`${pipeline.id}\`）
**总步数**：${total} 步
**执行模式**：全自动，步骤间自动传递上下文，无需用户介入`;

  const rules = `## 执行规则（必须严格遵守）

1. 按顺序执行以下全部 ${total} 个步骤，**不等待用户确认**
2. 每步完成后，用 \`<details>\` 标签折叠展示中间结果（见下方格式）
3. 将每步的**核心产出**（≤200字摘要）作为下一步的背景信息
4. 全部步骤完成后，输出完整合并报告`;

  const foldFormat = `## 每步输出格式

每个步骤完成后，使用如下格式：

\`\`\`
<details>
<summary>✅ 步骤 N：[Skill名称] — 已完成</summary>

[本步骤完整输出]

</details>
\`\`\``;

  const stepsSection = skills.map((skill, i) => {
    const stepNum = i + 1;
    const prevNote = i > 0
      ? `**前序输入**：使用步骤 ${i} 的核心产出（≤200字）作为本步骤的背景信息。\n\n`
      : '';
    const stepsContent = skill.steps
      .map((s, si) => {
        const title = s.title.replace(/^\d+[.、]\s*/, '');
        const indented = s.content.split('\n').map((l) => `   ${l}`).join('\n');
        return `   ${si + 1}. **${title}**\n${indented}`;
      })
      .join('\n\n');

    return `### 步骤 ${stepNum}/${total}：${skill.name}

${prevNote}**目标**：${skill.description}

**执行内容**：

${stepsContent}

**输出格式**：${skill.outputFormat}`;
  }).join('\n\n---\n\n');

  const reportTemplate = buildReportTemplate(pipeline, skills, context, false);
  const startCmd = `**立即开始执行步骤 1。**`;

  return [header, '---', rules, '---', foldFormat, '---', `## 步骤详情`, stepsSection, '---', reportTemplate, startCmd].join('\n\n');
}

/** 生成合并报告模板段落 */
function buildReportTemplate(
  pipeline: PipelineDefinition,
  skills: SkillDefinition[],
  context: string,
  isEn: boolean
): string {
  if (isEn) {
    const skillSections = skills
      .map((s) => `## ${s.nameEn.replace(/_/g, ' ')}\n[Full output]\n\n---`)
      .join('\n\n');
    return `## Final Output Requirements

After all steps complete, output the following merged report:

# Workflow Report — ${context}
> Pipeline: ${pipeline.name}

${skillSections}

*Auto-generated by Ethan Auto-Pilot*`;
  }

  const skillSections = skills
    .map((s) => `## ${s.name}\n[完整输出]\n\n---`)
    .join('\n\n');
  return `## 最终输出要求

全部步骤完成后，输出以下合并报告：

# 工作流执行报告 — ${context}
> Pipeline：${pipeline.name}

${skillSections}

*由 Ethan Auto-Pilot 自动生成*`;
}

/** 生成全部 Pipeline 的超级 prompt（依次串联所有 Pipeline） */
export function buildAllPipelinesAutopilotPrompt(
  pipelines: Array<{ pipeline: PipelineDefinition; skills: SkillDefinition[] }>,
  options: AutopilotOptions
): string {
  const { isEn = false } = options;
  const divider = '\n\n' + '═'.repeat(60) + '\n\n';

  const header = isEn
    ? `# Auto-Pilot — All Pipelines\n\n**Context**: ${options.context}\n**Mode**: Execute all ${pipelines.length} pipelines sequentially`
    : `# Auto-Pilot — 全部工作流\n\n**任务背景**：${options.context}\n**执行模式**：依次执行全部 ${pipelines.length} 条 Pipeline`;

  const sections = pipelines.map(({ pipeline, skills }, i) => {
    const label = isEn ? `Pipeline ${i + 1}/${pipelines.length}` : `Pipeline ${i + 1}/${pipelines.length}`;
    const prompt = buildAutopilotPrompt(pipeline, skills, options);
    return `# ${label}：${pipeline.name}\n\n${prompt}`;
  });

  return [header, ...sections].join(divider);
}
